name: CI
on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - main

jobs:
  cpp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1
        with:
          cmake-version: '3.30.0'
      - name: Install dependecies(Doxygen)
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen graphviz
      - name: Build and test
        run: |
          cmake -S . -B build
          cmake --build build
          cmake --install build --prefix install
          cd build && ctest --extra-verbose --output-on-failure
          